version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - $APP_PORT:$APP_PORT
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - .:/app