@id = 1

###

GET {{url}}/

###

GET {{url}}/tasks/

###

POST  {{url}}/tasks/
Content-Type: application/json

{
    "title": "",
    "description": "Task 1 description",
    "status": "pending"
}

###

DELETE {{url}}/tasks/1

###

PATCH {{url}}/tasks/1
Content-Type: application/json

{
    "status": "OPEN"
}

###